---
- hosts: all
  gather_facts: yes
  vars:
    node_type: unknown

  tasks:
  - name: Create drain log file
    file:
      path: /var/log/os-unsched-node.log
      state: touch
      owner: root
      group: root
      mode: 0644
      seuser: system_u
      serole: object_r
      setype: var_log_t
      selevel: s0
    
  - name: Create drain logrotate config
    blockinfile:
      dest: /etc/logrotate.d/os-unsched-node
      create: yes
      block: |
        /var/log/os-unsched-node.log {
            maxsize 50M
            weekly
            missingok
            rotate 5
            compress
            notifempty
            create 0644 root root
        }
  
  - name: Copy os_unsched_node.sh script
    template:
      src: os_unsched_node.sh.j2
      dest: /root/os_unsched_node.sh
      owner: root
      group: root
      mode: 0700
      seuser: system_u
      serole: object_r
      setype: initrc_exec_t
      selevel: s0

  - name: Create user service directory 
    file:
      path: /usr/local/lib/systemd/system/
      state: directory
      owner: root
      group: root
      mode: 0755
      seuser: unconfined_u
      serole: object_r
      setype: lib_t
      selevel: s0

  - name: Copy os-unsched-node service
    copy:
      src: os-unsched-node.service
      dest: /usr/local/lib/systemd/system/os-unsched-node.service
      owner: root
      group: root
      mode: 0640
      seuser: unconfined_u
      serole: object_r
      setype: lib_t
      selevel: s0

  - name: Start and enable service
    systemd:
      daemon_reload: yes
      name: os-unsched-node.service
      enabled: yes
      state: started

