---
- hosts: all
  gather_facts: yes
  vars:
    node_type: unknown

  tasks:
  - name: Check if kube config file exists
    stat:
      path: /root/.kube/config
    register: kube_config_exists

  - name: Create /root/.kube
    file:
      path: /root/.kube
      state: directory
      owner: root
      group: root
      mode: 0700
      seuser: system_u
      serole: object_r
      setype: admin_home_t
      selevel: s0
    when: not kube_config_exists.stat.exists

  - name: Copy kube config file
    copy:
      src: admin.kubeconfig
      dest: /root/.kube/config
      backup: yes
      owner: root
      group: root
      mode: 0700
      seuser: system_u
      serole: object_r
      setype: admin_home_t
      selevel: s0
    when: not kube_config_exists.stat.exists

  - name: Copy os_unsched_node.sh script
    copy:
      src: os_unsched_node.sh
      dest: /root/os_unsched_node.sh
      owner: root
      group: root
      mode: 0700
      seuser: system_u
      serole: object_r
      setype: initrc_exec_t
      selevel: s0

  - name: Create user service directory 
    file:
      path: /usr/local/lib/systemd/system/
      state: directory
      owner: root
      group: root
      mode: 0755
      seuser: unconfined_u
      serole: object_r
      setype: lib_t
      selevel: s0

  - name: Copy os-unsched-node service
    copy:
      src: os-unsched-node.service
      dest: /usr/local/lib/systemd/system/os-unsched-node.service
      owner: root
      group: root
      mode: 0640
      seuser: unconfined_u
      serole: object_r
      setype: lib_t
      selevel: s0

  - name: Start and enable service
    systemd:
      daemon_reload: yes
      name: os-unsched-node.service
      enabled: yes
      state: started

