---
- hosts: all
  gather_facts: yes
  vars:
    node_type: unknown

  tasks:
  - name: Check if drain_node cluster role exists
    shell:
      oc describe clusterPolicy default  | grep -q drain_node
    register: drain_node_exists
    ignore_errors: yes

  - name: Create drain_node yaml
    blockinfile:
      dest: /tmp/drain_node.yaml
      create: yes
      block: |
        apiVersion: v1
        kind: ClusterRole
        metadata:
          name: drain_node
        rules:
        - apiGroups:
          - ""
          attributeRestrictions: null
          resources:
          - nodes
          verbs:
          - get
          - list
          - patch
          - update
        - apiGroups:
          - ""
          attributeRestrictions: null
          resources:
          - pods
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
        - apiGroups:
          - ""
          attributeRestrictions: null
          resources:
          - pods/eviction
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
        - apiGroups:
          - ""
          attributeRestrictions: null
          resources:
          - replicationcontrollers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
    when: drain_node_exists.rc!=0

  - name: Create drain_node cluster role
    shell:
      oc create -f /tmp/drain_node.yaml
    when: drain_node_exists.rc!=0

  - name: Create the drain node account
    oc_serviceaccount:
      name: drain-node-sa
      namespace: openshift

  - name: Grant the drain serivce account access to drain_node
    oc_adm_policy_user:
      user: system:serviceaccount:openshift:drain-node-sa
      namespace: openshift
      resource_kind: cluster-role
      resource_name: drain_node

  - name: Remove drain_node yaml
    file:
      dest: /tmp/drain_node.yaml
      state: absent
    when: drain_node_exists.rc!=0


